spring.application.name=finance
spring.datasource.url=jdbc:postgresql://localhost:5432/finance_tracker
spring.datasource.username=${FINANCE_DB_USERNAME}
spring.datasource.password=${FINANCE_DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
jwt.secret=${FINANCE_JWT_SECRET}
jwt.expiration=3600000
